import type { CueId } from './cues';

/**
 * WHERE THE SOUND FILES GO.
 *
 * Drop the file in `assets/audio/` and replace the `null` with a require:
 *
 *     contradiction: require('../../assets/audio/contradiction.m4a'),
 *
 * Nothing else has to change. sound.ts treats a `null` entry as "this cue has no
 * sound yet" and returns without touching expo-audio, so the game behaves
 * identically with none, some, or all four filled in — which is why the settings
 * screen can ship a working volume control before a single asset exists.
 *
 * They are no longer null. Every file below is SYNTHESISED by
 * `tools/make-audio.mjs` and regenerated by running it — which is why there is
 * no licence question hanging over any of them, and why changing the text tone
 * is an edit to that script rather than a hunt through a sample pack.
 *
 * WAV rather than the m4a this note used to recommend: there is no encoder on
 * the build machine, and writing one for five sound effects is not a reasonable
 * trade. They are mono at 22.05kHz and total about 145KB, so the compression
 * would have bought very little anyway.
 *
 * The `Record<CueId, ...>` type is what guarantees a lookup here can never be
 * undefined; adding a sixth cue to CueId makes this a compile error until it is
 * listed. That is why no test asserts the same thing.
 */
export const CUE_SOURCES: Record<CueId, number | null> = {
  message: require('../../assets/audio/message.wav'),
  pin: require('../../assets/audio/pin.wav'),
  contradiction: require('../../assets/audio/contradiction.wav'),
  confession: require('../../assets/audio/confession.wav'),
  accusation: require('../../assets/audio/accusation.wav'),
  refused: require('../../assets/audio/refused.wav'),
  caseClosed: require('../../assets/audio/caseClosed.wav'),
  tap: require('../../assets/audio/tap.wav'),
};
